### ISSUE TITLE
Stat Editor Broken

### ISSUE THREAD

**Issue by mystikmunk** [Yeethan69/AIO#66] opened 2022-03-04 18:05 UTC
### What version of the aio were you running?

0.0.0.34

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

Ever since yesterday (March 3) The Stats Editor has stopped working. When you click Scan, nothing happens now. 
Newest update was working now Stat Editor seems to have died again. nothing happens when pressing Scan button.

**Comment by mystikmunk** [comment] 2022-03-04 23:01
New Update Fixed This Problem. Bug Report Can Be Closed!!

**Comment by mystikmunk** [comment] 2022-03-05 21:27
LoL It's doing it again! Stat Editor doesn't work. Pushing Scan does nothing now. :(

**Comment by ItsLogic** [comment] 2022-06-22 02:56
closing this as it was intended for an older version of the AIO. Stats editor has been updated since then
Reopen if the issue still exists and edit your post to mention the aio version

**Closed by ItsLogic** 2022-06-22 02:56 UTC
Labels: bug
