### ISSUE TITLE
[Bug]: FH5 Steam version can not max CR, only around 290,000,000

### ISSUE THREAD

**Issue by DavidLanz** [Yeethan69/AIO#77] opened 2022-04-23 01:17 UTC
### What version of the aio were you running?

0.0.0.40

### Game

FH5

### Game Version

Steam

### What is the bug?

[Bug]: FH5 Steam version can not max CR, only around 290,000,000

**Comment by ItsLogic** [comment] 2022-05-02 17:53
not a bug
Adding credits isnt even a feature its an unintentional part of an existing feature so if it doesnt give you max credits we wont fix it

**Closed by ItsLogic** 2022-05-02 17:53 UTC
Labels: bug, wontfix
