### ISSUE TITLE
AIO doent launch

### ISSUE THREAD

**Issue by xuvt** [Yeethan69/AIO#25] opened 2021-12-05 04:40 UTC
After 0.0.0.18 was released it sits at a low precentage and quits loading and it started happening on 0.0.0.17 and below.

**Comment by ItsLogic** [comment] 2021-12-05 07:00
Im assuming this is a duplicate of #24 so Im going to close the issue. If not just reopen it with more info to differentiate between them

**Closed by ItsLogic** 2021-12-05 07:00 UTC
